android {
    defaultConfig {
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
    }
}

dependencies {
    androidTestImplementation 'org.awaitility:awaitility:3.1.6'
    androidTestImplementation 'junit:junit:4.13.2'
    androidTestImplementation "org.mockito:mockito-android:5.17.0"
    androidTestImplementation 'org.nanohttpd:nanohttpd:2.3.1'
    androidTestImplementation 'androidx.test:core:1.6.1'
    androidTestImplementation 'androidx.test:rules:1.6.1'
}
